### PR TITLE
introduce vendoring again

### PR DESCRIPTION
**Pull request by alfredodeza**
execnet has now a dependency on `apipkg`, and the no-vendoring was breaking tools like ceph-deploy that benefits from vendoring since there aren't any packages for execnet or apipkg for both RPM and DEB distros.

There is no need to clone for a specific version, the libraries are included at their respective tags. Additionally, the `install_requires` has been added, so that when the `REMOTO_NO_VENDOR` env var is used, the regular packages are installed.

### CODE REVIEW

**Comment by ktdreyer** [comment]
I've built the apipkg / execnet / remoto stack for Ubuntu using the Debian packages. Was this mainly for Ubuntu?

**Comment by alfredodeza** [comment]
@ktdreyer I was unaware that there are now [packages everywhere for the remoto dependencies](https://ubuntu.pkgs.org/18.10/ubuntu-universe-amd64/python-execnet_1.4.1-4_all.deb.html).

Is there anything specific a ceph-deploy user would need to enable in order to have access to the packages? Hopefully not adding a PPA (but I guess that would also be fine, instead of having to vendor like this)

**Comment by vasukulkarni** [comment]
@ktdreyer what about RPMs?

**Comment by ktdreyer** [comment]
Thanks Alfredo. It looks like execnet and apipkg are just in Universe, so no PPA needed there.

[For RPMs](https://apps.fedoraproject.org/packages/python-execnet), Fedora has the latest execnet, and EPEL 7 has python-execnet-1.2.0-5.el7. I can submit an update to EPEL if we need something newer there.

**Comment by alfredodeza** [comment]
@ktdreyer those look fine to me, I guess we will need to update the packaging rules of ceph-deploy then. Will close this now, and follow up with a different PR with proper requirements defined. Thanks!

**Pull request closed without merging**
