### PR TITLE
Always use communicate vs. read to interact with subprocess pipe in process._remote_check

### LINKED ISSUE #62: Deadlock scenario in process._remote_check due to use of sub-process stdout/stderr pipes and read methods
The use of read methods on subprocess stdin/stderr pipes can cause deadlocks. The following warning is noted in the python [docs](https://docs.python.org/3/library/subprocess.html):

>Warning Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.

This can happen in [process.py._remote_check](https://github.com/alfredodeza/remoto/blob/797252945fb023335106dd82d24bad4643355b6b/remoto/process.py#L153). 

In this particular case, a deadlock occurs when the sub-process fills the OS stderr pipe buffer and is blocked while attempting to continue writing to stderr. In that case, stdout never reaches EOF and _remote_check is blocked trying to read from stdout.

This issue was discovered because it was causing a deadlock while attempting to upgrade a Ceph cluster from 15.2.10 -> 16.2.3.  This deadlock brought our whole upgrade process to a halt.

### PR DESCRIPTION
**Pull request by cfsnyder**
Fixes #62 

This bug is the root cause of https://tracker.ceph.com/issues/50526

### CODE REVIEW

**Comment by cfsnyder** [comment]
As noted in the associated issue, this bug was discovered while attempting to upgrade a Ceph cluster from 15.2.10 to 16.2.3. It was reproducible in 3 separate clusters. We applied this patch and upgrades on all clusters continued successfully.

**Comment by jmolmo** [comment]
This does not fix https://tracker.ceph.com/issues/50526 ( see comment in the bug )

I  miss more information about the problem that you expose in #62, it would be nice to have the log lines with the evidence of the deadlock. 
In any case your modification seems sensible.

**Comment by cfsnyder** [comment]
@jmolmo - I responded to your comment on the Ceph tracker ticket. Irrespective of whether you still disagree with the idea that this deadlock is the underlying cause of your problem in https://tracker.ceph.com/issues/50526, I hope that the additional detail provided in that comment is sufficient to illustrate the deadlock scenario that is possible prior to this fix. If you or @alfredodeza would like more evidence, I could spend some time reproducing the scenario again in order to provide GDB stacktraces of all relevant threads.

**Review by alfredodeza — APPROVED** [review]
Looks good! Thanks for taking the time to explain the pitfalls of using `stderr.read()` and `stdout.read()` that can cause a deadlock.

**Comment by alfredodeza** [comment]
@jmolmo @cfsnyder do you guys need a release ASAP for this? I'm happy to produce one right away or follow anything else you might need here

**Comment by ormandj** [comment]
@alfredodeza We do, it's resulting in issues with the stable release of Ceph. It'd be amazing if you could push a release out! Thank you so much for the quick response.

**Comment by alfredodeza** [comment]
I've pushed/released (and tagged) 1.2.1 See:  https://pypi.org/project/remoto/

**Pull request merged**
